name = "Amperage"

license = "MIT"
licenselink = ""

description = "Blazing fast SEO optimized theme with native AMP, structured data, service workers and i18n out of the box!"

homepage = "https://github.com/Robok3000/texter"

tags = ["blog", "personal", "responsive", 'minimal', 'clean', "simple", "google analytics", "light",
    "multilingual", "syntax highlighting", "fast", "customizable", "minimalistic", "technical", "amp",
    "white", "disqus", "starter"]

features = ["amp", "seo", "pwa", "structured data", "toc", "related content", "service-worker", "shortcodes",
    "syntax highlighting", "tags", "social share"]

min_version = "0.60.0"

[author]
    name = "RETER"
    homepage = ""
